CREATE TABLE IF NOT EXISTS `async_jobs` (
    `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    `job_key` CHAR(32) NOT NULL,
    `user_id` BIGINT UNSIGNED NOT NULL,
    `handler` VARCHAR(120) NOT NULL,
    `title` VARCHAR(255) NOT NULL,
    `status` VARCHAR(24) NOT NULL DEFAULT 'queued',
    `pid` BIGINT NULL DEFAULT NULL,
    `payload_json` LONGTEXT NOT NULL,
    `progress_bars_json` LONGTEXT NULL DEFAULT NULL,
    `warnings_json` LONGTEXT NULL DEFAULT NULL,
    `error_message` TEXT NULL DEFAULT NULL,
    `download_name` VARCHAR(255) NULL DEFAULT NULL,
    `download_type` VARCHAR(16) NULL DEFAULT NULL,
    `download_path` TEXT NULL DEFAULT NULL,
    `started_at` DATETIME NULL DEFAULT NULL,
    `finished_at` DATETIME NULL DEFAULT NULL,
    `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    UNIQUE KEY `async_jobs_job_key_unique` (`job_key`),
    KEY `async_jobs_user_id_idx` (`user_id`),
    KEY `async_jobs_status_idx` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
